"""empty message

Revision ID: 0049390d7703
Revises: 
Create Date: 2018-08-19 18:11:58.956638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0049390d7703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('deletion_marker', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('deleted_by', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('banner_img', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_index(op.f('ix_category_created_by'), 'category', ['created_by'], unique=False)
    op.create_index(op.f('ix_category_deleted_by'), 'category', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_category_updated_by'), 'category', ['updated_by'], unique=False)
    op.create_table('tender',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('deletion_marker', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('deleted_by', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('application_close_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.public_id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_index(op.f('ix_tender_created_by'), 'tender', ['created_by'], unique=False)
    op.create_index(op.f('ix_tender_deleted_by'), 'tender', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_tender_updated_by'), 'tender', ['updated_by'], unique=False)
    op.create_table('bid',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('deletion_marker', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('deleted_by', sa.String(length=200), nullable=True),
    sa.Column('tender_id', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.public_id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_index(op.f('ix_bid_created_by'), 'bid', ['created_by'], unique=False)
    op.create_index(op.f('ix_bid_deleted_by'), 'bid', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_bid_supplier_id'), 'bid', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_bid_tender_id'), 'bid', ['tender_id'], unique=False)
    op.create_index(op.f('ix_bid_updated_by'), 'bid', ['updated_by'], unique=False)
    op.create_table('document',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('deletion_marker', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('deleted_by', sa.String(length=200), nullable=True),
    sa.Column('tender_id', sa.String(length=100), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('doc_url', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.public_id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_index(op.f('ix_document_created_by'), 'document', ['created_by'], unique=False)
    op.create_index(op.f('ix_document_deleted_by'), 'document', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_document_updated_by'), 'document', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_updated_by'), table_name='document')
    op.drop_index(op.f('ix_document_deleted_by'), table_name='document')
    op.drop_index(op.f('ix_document_created_by'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_bid_updated_by'), table_name='bid')
    op.drop_index(op.f('ix_bid_tender_id'), table_name='bid')
    op.drop_index(op.f('ix_bid_supplier_id'), table_name='bid')
    op.drop_index(op.f('ix_bid_deleted_by'), table_name='bid')
    op.drop_index(op.f('ix_bid_created_by'), table_name='bid')
    op.drop_table('bid')
    op.drop_index(op.f('ix_tender_updated_by'), table_name='tender')
    op.drop_index(op.f('ix_tender_deleted_by'), table_name='tender')
    op.drop_index(op.f('ix_tender_created_by'), table_name='tender')
    op.drop_table('tender')
    op.drop_index(op.f('ix_category_updated_by'), table_name='category')
    op.drop_index(op.f('ix_category_deleted_by'), table_name='category')
    op.drop_index(op.f('ix_category_created_by'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
