"""empty message

Revision ID: 8ce1977cf907
Revises: 4b598e764b16
Create Date: 2018-08-21 16:57:28.352409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce1977cf907'
down_revision = '4b598e764b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('o_auth_client',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('secret', sa.String(length=100), nullable=True),
    sa.Column('redirect', sa.Text(), nullable=True),
    sa.Column('personal_access_client', sa.Integer(), nullable=True),
    sa.Column('password_client', sa.Integer(), nullable=True),
    sa.Column('revoked', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_public_id'), 'password_reset', ['public_id'], unique=True)
    op.create_index(op.f('ix_password_reset_token'), 'password_reset', ['token'], unique=True)
    op.create_table('usertype',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('deletion_marker', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('deleted_by', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_index(op.f('ix_usertype_created_by'), 'usertype', ['created_by'], unique=False)
    op.create_index(op.f('ix_usertype_deleted_by'), 'usertype', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_usertype_updated_by'), 'usertype', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usertype_updated_by'), table_name='usertype')
    op.drop_index(op.f('ix_usertype_deleted_by'), table_name='usertype')
    op.drop_index(op.f('ix_usertype_created_by'), table_name='usertype')
    op.drop_table('usertype')
    op.drop_index(op.f('ix_password_reset_token'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_public_id'), table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_table('o_auth_client')
    # ### end Alembic commands ###
