"""empty message

Revision ID: d4b5958df9f6
Revises: ebe29b8516b5
Create Date: 2018-10-06 15:45:12.728246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b5958df9f6'
down_revision = 'ebe29b8516b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_document',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('deletion_marker', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('deleted_by', sa.String(length=200), nullable=True),
    sa.Column('bid_id', sa.String(length=100), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('doc_url', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bid.public_id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_index(op.f('ix_bid_document_created_by'), 'bid_document', ['created_by'], unique=False)
    op.create_index(op.f('ix_bid_document_deleted_by'), 'bid_document', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_bid_document_updated_by'), 'bid_document', ['updated_by'], unique=False)
    op.alter_column('bid', 'amount',
               existing_type=sa.REAL(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bid', 'amount',
               existing_type=sa.REAL(),
               nullable=False)
    op.drop_index(op.f('ix_bid_document_updated_by'), table_name='bid_document')
    op.drop_index(op.f('ix_bid_document_deleted_by'), table_name='bid_document')
    op.drop_index(op.f('ix_bid_document_created_by'), table_name='bid_document')
    op.drop_table('bid_document')
    # ### end Alembic commands ###
