"""empty message

Revision ID: ebe29b8516b5
Revises: a93131bc034d
Create Date: 2018-09-19 20:31:21.116837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe29b8516b5'
down_revision = 'a93131bc034d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('amount', sa.Float(precision=6, asdecimal=2), nullable=False))
    op.add_column('bid', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'duration')
    op.drop_column('bid', 'amount')
    # ### end Alembic commands ###
